spring:
  application:
    name: weather.api
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
  cloud:
    openfeign:
      client:
        config:
          weatherClient:
            url: "https://weather.visualcrossing.com"
            default-query-params:
              key: {API_KEY}


